### ISSUE TITLE
Lỗi vẫn hiển thị nhập info sau khi đã nhập

### ISSUE THREAD

**Issue by hieuhust** [hieuhust/kinhnguyet#1]
1. Vào app nhập info cho đến màn hình của view pager
2. Thoát app và kill app đi bằng task manager
3. Vào lại app
3.1 Thực tế: sau khi vào lại vẫn hiển thị màn hình nhập thông tin
3.2 Mong đợi : Không hiển thị màn hình nhập thông tin khi đã nhập 1 lần rồi

**Comment by andaupro** [comment]
fixed
