### ISSUE TITLE
Lỗi chưa cập nhật ngày tháng khi để mặc định

### ISSUE THREAD

**Issue by hieuhust** [hieuhust/kinhnguyet#2]
1. Vào màn hình nhập thông tin
2. Không chọn ngày tháng mà để mặc định rồi bấm next
2.1 Thực tế: Báo chưa nhập ngày tháng
2.2 Mong đợi: Vẫn báo thành công và lấy luôn ngày tháng mặc định

**Comment by andaupro** [comment]
folllow to app gốc
