### ISSUE TITLE
Lỗi báo giá trị nhập vào không hợp lệ nhưng không giải thích

### ISSUE THREAD

**Issue by hieuhust** [hieuhust/kinhnguyet#3]
1. Bật app vào màn hình creat new user
2. Nhập chiều cao là 40 cm
3. Nhập các thông tin khác
4. Bấm next
4.1 Actual: Chỉ báo giá trị chiều cao không hợp lệ những không nói khoảng bao nhiêu thì đúng
4.2 Expect: Nói rõ cả các khoảng hợp lệ
Lỗi này xảy ra ở các màn hình tiếp theo và ở các trường thông tin khác nữa

**Comment by andaupro** [comment]
khi chiều cao không hợp lệ có nghĩa sẽ là người dùng nhập sai và chỉ cần nhắc nhở người dùng hãy nhập đúng chiều cao của mình. Còn nếu người dùng nhập đúng rồi mà vẫn báo vậy thì đó là issue của app. 
trong trường hợp này, không có người nào có chiều cao dưới 1m cả ==> maintain as app concept!
